linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.3

linters:
  enable-all: true

issues:
  exclude-use-default: false

  exclude-rules:
    # Exclude some linters from running on tests files.
    # - path: gringotts-server/cmd/root.go
    #   linters:
    #     - gochecknoglobals
    #   text: "rootCmd"
    - linters:
        - gosec
      text: "unhandled"
      source: ".WriteString\\("