// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MonitorItemType int32

const (
	MonitorItemType_SELF        MonitorItemType = 0
	MonitorItemType_THIRD_PARTY MonitorItemType = 1
)

var MonitorItemType_name = map[int32]string{
	0: "SELF",
	1: "THIRD_PARTY",
}

var MonitorItemType_value = map[string]int32{
	"SELF":        0,
	"THIRD_PARTY": 1,
}

func (x MonitorItemType) String() string {
	return proto.EnumName(MonitorItemType_name, int32(x))
}

func (MonitorItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type SelfMonitorFunc int32

const (
	SelfMonitorFunc_CPU SelfMonitorFunc = 0
	SelfMonitorFunc_MEM SelfMonitorFunc = 1
)

var SelfMonitorFunc_name = map[int32]string{
	0: "CPU",
	1: "MEM",
}

var SelfMonitorFunc_value = map[string]int32{
	"CPU": 0,
	"MEM": 1,
}

func (x SelfMonitorFunc) String() string {
	return proto.EnumName(SelfMonitorFunc_name, int32(x))
}

func (SelfMonitorFunc) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type File struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Sha1Hash             string   `protobuf:"bytes,2,opt,name=sha1_hash,json=sha1Hash,proto3" json:"sha1_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetSha1Hash() string {
	if m != nil {
		return m.Sha1Hash
	}
	return ""
}

type FileChunk struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunk.Unmarshal(m, b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
}
func (m *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(m, src)
}
func (m *FileChunk) XXX_Size() int {
	return xxx_messageInfo_FileChunk.Size(m)
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HeartBeatRequest struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRequest) Reset()         { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()    {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *HeartBeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRequest.Unmarshal(m, b)
}
func (m *HeartBeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartBeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequest.Merge(m, src)
}
func (m *HeartBeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRequest.Size(m)
}
func (m *HeartBeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequest proto.InternalMessageInfo

func (m *HeartBeatRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *HeartBeatRequest) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *HeartBeatRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MonitorInfo struct {
	Items                []*MonitorItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MonitorInfo) Reset()         { *m = MonitorInfo{} }
func (m *MonitorInfo) String() string { return proto.CompactTextString(m) }
func (*MonitorInfo) ProtoMessage()    {}
func (*MonitorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *MonitorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorInfo.Unmarshal(m, b)
}
func (m *MonitorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorInfo.Marshal(b, m, deterministic)
}
func (m *MonitorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorInfo.Merge(m, src)
}
func (m *MonitorInfo) XXX_Size() int {
	return xxx_messageInfo_MonitorInfo.Size(m)
}
func (m *MonitorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorInfo proto.InternalMessageInfo

func (m *MonitorInfo) GetItems() []*MonitorItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type MonitorItem struct {
	TaskId                    int64           `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecIntervalSecond        int64           `protobuf:"varint,2,opt,name=exec_interval_second,json=execIntervalSecond,proto3" json:"exec_interval_second,omitempty"`
	Type                      MonitorItemType `protobuf:"varint,3,opt,name=type,proto3,enum=MonitorItemType" json:"type,omitempty"`
	SelfFunc                  SelfMonitorFunc `protobuf:"varint,4,opt,name=self_func,json=selfFunc,proto3,enum=SelfMonitorFunc" json:"self_func,omitempty"`
	SelfFuncConfig            string          `protobuf:"bytes,5,opt,name=self_func_config,json=selfFuncConfig,proto3" json:"self_func_config,omitempty"`
	ThirdPartyFuncName        string          `protobuf:"bytes,6,opt,name=third_party_func_name,json=thirdPartyFuncName,proto3" json:"third_party_func_name,omitempty"`
	ThirdPartyDependencyFiles string          `protobuf:"bytes,7,opt,name=third_party_dependency_files,json=thirdPartyDependencyFiles,proto3" json:"third_party_dependency_files,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}        `json:"-"`
	XXX_unrecognized          []byte          `json:"-"`
	XXX_sizecache             int32           `json:"-"`
}

func (m *MonitorItem) Reset()         { *m = MonitorItem{} }
func (m *MonitorItem) String() string { return proto.CompactTextString(m) }
func (*MonitorItem) ProtoMessage()    {}
func (*MonitorItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *MonitorItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorItem.Unmarshal(m, b)
}
func (m *MonitorItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorItem.Marshal(b, m, deterministic)
}
func (m *MonitorItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorItem.Merge(m, src)
}
func (m *MonitorItem) XXX_Size() int {
	return xxx_messageInfo_MonitorItem.Size(m)
}
func (m *MonitorItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorItem.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorItem proto.InternalMessageInfo

func (m *MonitorItem) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *MonitorItem) GetExecIntervalSecond() int64 {
	if m != nil {
		return m.ExecIntervalSecond
	}
	return 0
}

func (m *MonitorItem) GetType() MonitorItemType {
	if m != nil {
		return m.Type
	}
	return MonitorItemType_SELF
}

func (m *MonitorItem) GetSelfFunc() SelfMonitorFunc {
	if m != nil {
		return m.SelfFunc
	}
	return SelfMonitorFunc_CPU
}

func (m *MonitorItem) GetSelfFuncConfig() string {
	if m != nil {
		return m.SelfFuncConfig
	}
	return ""
}

func (m *MonitorItem) GetThirdPartyFuncName() string {
	if m != nil {
		return m.ThirdPartyFuncName
	}
	return ""
}

func (m *MonitorItem) GetThirdPartyDependencyFiles() string {
	if m != nil {
		return m.ThirdPartyDependencyFiles
	}
	return ""
}

type HeartBeatResponse struct {
	ServerId             string       `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ConfigVersion        string       `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ConfigChangeTime     int64        `protobuf:"varint,3,opt,name=config_change_time,json=configChangeTime,proto3" json:"config_change_time,omitempty"`
	MonitorInfo          *MonitorInfo `protobuf:"bytes,4,opt,name=monitor_info,json=monitorInfo,proto3" json:"monitor_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HeartBeatResponse) Reset()         { *m = HeartBeatResponse{} }
func (m *HeartBeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResponse) ProtoMessage()    {}
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *HeartBeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResponse.Unmarshal(m, b)
}
func (m *HeartBeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartBeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResponse.Merge(m, src)
}
func (m *HeartBeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResponse.Size(m)
}
func (m *HeartBeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResponse proto.InternalMessageInfo

func (m *HeartBeatResponse) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *HeartBeatResponse) GetConfigVersion() string {
	if m != nil {
		return m.ConfigVersion
	}
	return ""
}

func (m *HeartBeatResponse) GetConfigChangeTime() int64 {
	if m != nil {
		return m.ConfigChangeTime
	}
	return 0
}

func (m *HeartBeatResponse) GetMonitorInfo() *MonitorInfo {
	if m != nil {
		return m.MonitorInfo
	}
	return nil
}

type RegisterRequest struct {
	AgentID              string                       `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	HostName             string                       `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	HostUUID             string                       `protobuf:"bytes,3,opt,name=hostUUID,proto3" json:"hostUUID,omitempty"`
	Os                   string                       `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Platform             string                       `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformFamily       string                       `protobuf:"bytes,6,opt,name=platformFamily,proto3" json:"platformFamily,omitempty"`
	PlatformVersion      string                       `protobuf:"bytes,7,opt,name=platformVersion,proto3" json:"platformVersion,omitempty"`
	KernelVersion        string                       `protobuf:"bytes,8,opt,name=kernelVersion,proto3" json:"kernelVersion,omitempty"`
	VirtualizationSystem string                       `protobuf:"bytes,9,opt,name=virtualizationSystem,proto3" json:"virtualizationSystem,omitempty"`
	VirtualizationRole   string                       `protobuf:"bytes,10,opt,name=virtualizationRole,proto3" json:"virtualizationRole,omitempty"`
	Interfaces           []*RegisterRequest_Interface `protobuf:"bytes,111,rep,name=Interfaces,proto3" json:"Interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *RegisterRequest) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *RegisterRequest) GetHostUUID() string {
	if m != nil {
		return m.HostUUID
	}
	return ""
}

func (m *RegisterRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *RegisterRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *RegisterRequest) GetPlatformFamily() string {
	if m != nil {
		return m.PlatformFamily
	}
	return ""
}

func (m *RegisterRequest) GetPlatformVersion() string {
	if m != nil {
		return m.PlatformVersion
	}
	return ""
}

func (m *RegisterRequest) GetKernelVersion() string {
	if m != nil {
		return m.KernelVersion
	}
	return ""
}

func (m *RegisterRequest) GetVirtualizationSystem() string {
	if m != nil {
		return m.VirtualizationSystem
	}
	return ""
}

func (m *RegisterRequest) GetVirtualizationRole() string {
	if m != nil {
		return m.VirtualizationRole
	}
	return ""
}

func (m *RegisterRequest) GetInterfaces() []*RegisterRequest_Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type RegisterRequest_Interface struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HardwareAddr         string   `protobuf:"bytes,2,opt,name=hardwareAddr,proto3" json:"hardwareAddr,omitempty"`
	IpAddrs              []string `protobuf:"bytes,3,rep,name=ipAddrs,proto3" json:"ipAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest_Interface) Reset()         { *m = RegisterRequest_Interface{} }
func (m *RegisterRequest_Interface) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest_Interface) ProtoMessage()    {}
func (*RegisterRequest_Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6, 0}
}

func (m *RegisterRequest_Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest_Interface.Unmarshal(m, b)
}
func (m *RegisterRequest_Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest_Interface.Marshal(b, m, deterministic)
}
func (m *RegisterRequest_Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest_Interface.Merge(m, src)
}
func (m *RegisterRequest_Interface) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest_Interface.Size(m)
}
func (m *RegisterRequest_Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest_Interface proto.InternalMessageInfo

func (m *RegisterRequest_Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest_Interface) GetHardwareAddr() string {
	if m != nil {
		return m.HardwareAddr
	}
	return ""
}

func (m *RegisterRequest_Interface) GetIpAddrs() []string {
	if m != nil {
		return m.IpAddrs
	}
	return nil
}

type RegisterResponse struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConfigVersion        string   `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *RegisterResponse) GetConfigVersion() string {
	if m != nil {
		return m.ConfigVersion
	}
	return ""
}

func init() {
	proto.RegisterEnum("MonitorItemType", MonitorItemType_name, MonitorItemType_value)
	proto.RegisterEnum("SelfMonitorFunc", SelfMonitorFunc_name, SelfMonitorFunc_value)
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterType((*FileChunk)(nil), "FileChunk")
	proto.RegisterType((*HeartBeatRequest)(nil), "HeartBeatRequest")
	proto.RegisterType((*MonitorInfo)(nil), "MonitorInfo")
	proto.RegisterType((*MonitorItem)(nil), "MonitorItem")
	proto.RegisterType((*HeartBeatResponse)(nil), "HeartBeatResponse")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterRequest_Interface)(nil), "RegisterRequest.Interface")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 815 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xef, 0x6e, 0xe3, 0x44,
	0x10, 0xbf, 0x34, 0x69, 0x1b, 0x4f, 0xd3, 0xc4, 0x1d, 0x1d, 0xc2, 0x17, 0x90, 0xa8, 0x7c, 0x07,
	0x8a, 0x4e, 0x87, 0xef, 0x1a, 0xbe, 0xf1, 0x05, 0x8e, 0xe6, 0xaa, 0x46, 0xa2, 0xa8, 0x72, 0x53,
	0x24, 0x3e, 0x80, 0xb5, 0xc4, 0xe3, 0x78, 0x55, 0x7b, 0x37, 0x78, 0x37, 0x3d, 0xc2, 0x03, 0xf0,
	0x06, 0xbc, 0x0a, 0x2f, 0xc1, 0x4b, 0xa1, 0x5d, 0x6f, 0xfe, 0x34, 0x45, 0xe8, 0x3e, 0x75, 0xe6,
	0xf7, 0xfb, 0xad, 0x77, 0x3a, 0xbf, 0xd9, 0x09, 0x1c, 0x97, 0xa4, 0x14, 0x9b, 0x51, 0x34, 0xaf,
	0xa4, 0x96, 0xe1, 0xb7, 0xd0, 0xba, 0xe0, 0x05, 0xe1, 0x27, 0xe0, 0x65, 0xbc, 0xa0, 0x44, 0xb0,
	0x92, 0x82, 0xc6, 0x69, 0x63, 0xe0, 0xc5, 0x6d, 0x03, 0xfc, 0xc0, 0x4a, 0x4b, 0xaa, 0x9c, 0x9d,
	0x25, 0x39, 0x53, 0x79, 0xb0, 0x57, 0x93, 0x06, 0xb8, 0x64, 0x2a, 0x0f, 0x3f, 0x03, 0xcf, 0x7c,
	0xe1, 0x3c, 0x5f, 0x88, 0x3b, 0x44, 0x68, 0xa5, 0x4c, 0x33, 0xfb, 0x85, 0x4e, 0x6c, 0xe3, 0xf0,
	0x17, 0xf0, 0x2f, 0x89, 0x55, 0xfa, 0x3b, 0x62, 0x3a, 0xa6, 0xdf, 0x16, 0xa4, 0x34, 0x3e, 0x83,
	0x36, 0x9b, 0x91, 0xd0, 0x09, 0x4f, 0xdd, 0x6d, 0x87, 0x36, 0x1f, 0xa7, 0xe6, 0xb2, 0x5c, 0x2a,
	0x5d, 0x57, 0xe2, 0x2e, 0x33, 0x80, 0xad, 0x04, 0xa1, 0xa5, 0x79, 0x49, 0x41, 0xf3, 0xb4, 0x31,
	0x68, 0xc6, 0x36, 0x0e, 0xcf, 0xe0, 0xe8, 0x4a, 0x0a, 0xae, 0x65, 0x35, 0x16, 0x99, 0xc4, 0x10,
	0xf6, 0xc7, 0x9a, 0x4a, 0x15, 0x34, 0x4e, 0x9b, 0x83, 0xa3, 0x61, 0x27, 0x5a, 0x91, 0x9a, 0xca,
	0xb8, 0xa6, 0xc2, 0x7f, 0xf6, 0x36, 0x67, 0x34, 0x95, 0xf8, 0x31, 0x1c, 0x6a, 0xa6, 0xee, 0x56,
	0xd5, 0x34, 0xe3, 0x03, 0x93, 0x8e, 0x53, 0x7c, 0x03, 0x4f, 0xe9, 0x77, 0x9a, 0x26, 0x5c, 0x68,
	0xaa, 0xee, 0x59, 0x91, 0x28, 0x9a, 0x4a, 0x91, 0xda, 0xba, 0x9a, 0x31, 0x1a, 0x6e, 0xec, 0xa8,
	0x1b, 0xcb, 0xe0, 0x0b, 0x68, 0xe9, 0xe5, 0xbc, 0xae, 0xb0, 0x3b, 0xf4, 0xb7, 0x6f, 0x9f, 0x2c,
	0xe7, 0x14, 0x5b, 0x16, 0xbf, 0x04, 0x4f, 0x51, 0x91, 0x25, 0xd9, 0x42, 0x4c, 0x83, 0x96, 0x93,
	0xde, 0x50, 0x91, 0x39, 0xf9, 0xc5, 0x42, 0x4c, 0xe3, 0xb6, 0x91, 0x98, 0x08, 0x07, 0xe0, 0xaf,
	0xe5, 0xc9, 0x54, 0x8a, 0x8c, 0xcf, 0x82, 0x7d, 0xdb, 0x9a, 0xee, 0x4a, 0x73, 0x6e, 0x51, 0x3c,
	0x83, 0x8f, 0x74, 0xce, 0xab, 0x34, 0x99, 0xb3, 0x4a, 0x2f, 0xeb, 0x03, 0xb6, 0x93, 0x07, 0x56,
	0x8e, 0x96, 0xbc, 0x36, 0x9c, 0x39, 0x64, 0x7b, 0xfa, 0x0d, 0x7c, 0xba, 0x7d, 0x24, 0xa5, 0x39,
	0x89, 0x94, 0xc4, 0x74, 0x99, 0x98, 0x01, 0x50, 0xc1, 0xa1, 0x3d, 0xf9, 0x6c, 0x73, 0x72, 0xb4,
	0x56, 0x18, 0xe3, 0x55, 0xf8, 0x77, 0x03, 0x4e, 0xb6, 0x1c, 0x56, 0x73, 0x29, 0x54, 0x3d, 0x34,
	0x54, 0xdd, 0x53, 0xb5, 0xf1, 0xb8, 0x5d, 0x03, 0xe3, 0x14, 0x3f, 0x87, 0x6e, 0xfd, 0x6f, 0x24,
	0xf7, 0x54, 0x29, 0x2e, 0x85, 0x73, 0xfa, 0xb8, 0x46, 0x7f, 0xac, 0x41, 0x7c, 0x05, 0xe8, 0x64,
	0xd3, 0x9c, 0x89, 0x19, 0x25, 0x5b, 0xe6, 0xfb, 0x35, 0x73, 0x6e, 0x89, 0x09, 0x2f, 0x09, 0x5f,
	0x43, 0xa7, 0xac, 0xdb, 0x97, 0x70, 0x91, 0x49, 0xdb, 0xd7, 0xed, 0x01, 0x10, 0x99, 0x8c, 0x8f,
	0xca, 0x4d, 0x12, 0xfe, 0xd9, 0x82, 0x5e, 0x4c, 0x33, 0xae, 0x34, 0x55, 0xab, 0xc9, 0x0c, 0xc0,
	0x4d, 0xe2, 0xe8, 0xe1, 0x60, 0x8e, 0xb0, 0x0f, 0xeb, 0x39, 0x7c, 0x34, 0x97, 0x8e, 0xbb, 0xbd,
	0x1d, 0x8f, 0x6c, 0x79, 0x8e, 0x33, 0x39, 0x76, 0x61, 0x4f, 0x2a, 0x5b, 0x8c, 0x17, 0xef, 0x49,
	0x65, 0xb4, 0xf3, 0x82, 0xe9, 0x4c, 0x56, 0xa5, 0x33, 0x71, 0x9d, 0xe3, 0x17, 0xd0, 0x5d, 0xc5,
	0x17, 0xac, 0xe4, 0xc5, 0xd2, 0xf9, 0xb6, 0x83, 0xe2, 0x00, 0x7a, 0x2b, 0xc4, 0xf5, 0xca, 0xd9,
	0xb4, 0x0b, 0xe3, 0x0b, 0x38, 0xbe, 0xa3, 0x4a, 0x50, 0xb1, 0xd2, 0xb5, 0xeb, 0x46, 0x3f, 0x00,
	0x71, 0x08, 0x4f, 0xef, 0x79, 0xa5, 0x17, 0xac, 0xe0, 0x7f, 0x30, 0xcd, 0xa5, 0xb8, 0x59, 0x2a,
	0x4d, 0x65, 0xe0, 0x59, 0xf1, 0x7f, 0x72, 0x18, 0x01, 0x3e, 0xc4, 0x63, 0x59, 0x50, 0x00, 0xf5,
	0x9c, 0x3d, 0x66, 0xf0, 0x6b, 0x00, 0xfb, 0x56, 0x32, 0x36, 0x25, 0x15, 0x48, 0xfb, 0x3a, 0xfb,
	0xd1, 0x4e, 0xff, 0xa3, 0xb5, 0x24, 0xde, 0x52, 0xf7, 0x7f, 0x06, 0x6f, 0x9d, 0x99, 0x25, 0xb0,
	0xb5, 0xa6, 0x6c, 0x8c, 0x21, 0x74, 0x72, 0x56, 0xa5, 0xef, 0x59, 0x45, 0x6f, 0xd3, 0xb4, 0x72,
	0x06, 0x3d, 0xc0, 0x8c, 0xb5, 0x7c, 0x6e, 0x22, 0x15, 0x34, 0x4f, 0x9b, 0xc6, 0x5a, 0x97, 0x86,
	0x13, 0xf0, 0x37, 0x75, 0xb8, 0xf9, 0xfd, 0x9f, 0x15, 0xf5, 0x61, 0xd3, 0xfb, 0xf2, 0x15, 0xf4,
	0x76, 0x5e, 0x3f, 0xb6, 0xa1, 0x75, 0xf3, 0xee, 0xfb, 0x0b, 0xff, 0x09, 0xf6, 0xe0, 0x68, 0x72,
	0x39, 0x8e, 0x47, 0xc9, 0xf5, 0xdb, 0x78, 0xf2, 0x93, 0xdf, 0x78, 0xf9, 0x1c, 0x7a, 0x3b, 0x0b,
	0x00, 0x0f, 0xa1, 0x79, 0x7e, 0x7d, 0xeb, 0x3f, 0x31, 0xc1, 0xd5, 0xbb, 0x2b, 0xbf, 0x31, 0xfc,
	0xab, 0x01, 0xde, 0xac, 0xe2, 0x62, 0x26, 0xb5, 0x56, 0x38, 0x04, 0x6f, 0xfd, 0xee, 0xf0, 0x24,
	0xda, 0xdd, 0xb2, 0x7d, 0x8c, 0x1e, 0x3f, 0xcb, 0xe7, 0xd0, 0x19, 0xc9, 0xf7, 0xa2, 0x90, 0x2c,
	0xb5, 0x8b, 0x7f, 0x3f, 0x32, 0x7f, 0xfa, 0x10, 0xad, 0x97, 0xf8, 0x9b, 0x06, 0xbe, 0x86, 0xf6,
	0xaa, 0x1f, 0xe8, 0xef, 0x5a, 0xd4, 0x3f, 0x89, 0x76, 0x9b, 0xf5, 0xeb, 0x81, 0xfd, 0x35, 0xf9,
	0xea, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x19, 0xeb, 0xf2, 0x5e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GringottsClient is the client API for Gringotts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GringottsClient interface {
	HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error)
	DownloadFile(ctx context.Context, in *File, opts ...grpc.CallOption) (Gringotts_DownloadFileClient, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type gringottsClient struct {
	cc *grpc.ClientConn
}

func NewGringottsClient(cc *grpc.ClientConn) GringottsClient {
	return &gringottsClient{cc}
}

func (c *gringottsClient) HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error) {
	out := new(HeartBeatResponse)
	err := c.cc.Invoke(ctx, "/gringotts/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gringottsClient) DownloadFile(ctx context.Context, in *File, opts ...grpc.CallOption) (Gringotts_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gringotts_serviceDesc.Streams[0], "/gringotts/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &gringottsDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gringotts_DownloadFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type gringottsDownloadFileClient struct {
	grpc.ClientStream
}

func (x *gringottsDownloadFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gringottsClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/gringotts/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GringottsServer is the server API for Gringotts service.
type GringottsServer interface {
	HeartBeat(context.Context, *HeartBeatRequest) (*HeartBeatResponse, error)
	DownloadFile(*File, Gringotts_DownloadFileServer) error
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedGringottsServer can be embedded to have forward compatible implementations.
type UnimplementedGringottsServer struct {
}

func (*UnimplementedGringottsServer) HeartBeat(ctx context.Context, req *HeartBeatRequest) (*HeartBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (*UnimplementedGringottsServer) DownloadFile(req *File, srv Gringotts_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (*UnimplementedGringottsServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterGringottsServer(s *grpc.Server, srv GringottsServer) {
	s.RegisterService(&_Gringotts_serviceDesc, srv)
}

func _Gringotts_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GringottsServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gringotts/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GringottsServer).HeartBeat(ctx, req.(*HeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gringotts_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(File)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GringottsServer).DownloadFile(m, &gringottsDownloadFileServer{stream})
}

type Gringotts_DownloadFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type gringottsDownloadFileServer struct {
	grpc.ServerStream
}

func (x *gringottsDownloadFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _Gringotts_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GringottsServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gringotts/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GringottsServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gringotts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gringotts",
	HandlerType: (*GringottsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartBeat",
			Handler:    _Gringotts_HeartBeat_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Gringotts_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _Gringotts_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}
