// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobRunningState int32

const (
	JobRunningState_OK    JobRunningState = 0
	JobRunningState_Error JobRunningState = 1
)

var JobRunningState_name = map[int32]string{
	0: "OK",
	1: "Error",
}

var JobRunningState_value = map[string]int32{
	"OK":    0,
	"Error": 1,
}

func (x JobRunningState) String() string {
	return proto.EnumName(JobRunningState_name, int32(x))
}

func (JobRunningState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type JobRunner int32

const (
	JobRunner_Telegraf JobRunner = 0
	JobRunner_Datadog  JobRunner = 1
)

var JobRunner_name = map[int32]string{
	0: "Telegraf",
	1: "Datadog",
}

var JobRunner_value = map[string]int32{
	"Telegraf": 0,
	"Datadog":  1,
}

func (x JobRunner) String() string {
	return proto.EnumName(JobRunner_name, int32(x))
}

func (JobRunner) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type File struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Sha1Hash             string   `protobuf:"bytes,2,opt,name=sha1_hash,json=sha1Hash,proto3" json:"sha1_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetSha1Hash() string {
	if m != nil {
		return m.Sha1Hash
	}
	return ""
}

type FileChunk struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunk.Unmarshal(m, b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
}
func (m *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(m, src)
}
func (m *FileChunk) XXX_Size() int {
	return xxx_messageInfo_FileChunk.Size(m)
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HeartBeatRequest struct {
	AgentID              string            `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	Jobs                 []*JobRunningInfo `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	ClientTime           int64             `protobuf:"varint,3,opt,name=clientTime,proto3" json:"clientTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HeartBeatRequest) Reset()         { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()    {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *HeartBeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRequest.Unmarshal(m, b)
}
func (m *HeartBeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartBeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequest.Merge(m, src)
}
func (m *HeartBeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRequest.Size(m)
}
func (m *HeartBeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequest proto.InternalMessageInfo

func (m *HeartBeatRequest) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *HeartBeatRequest) GetJobs() []*JobRunningInfo {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *HeartBeatRequest) GetClientTime() int64 {
	if m != nil {
		return m.ClientTime
	}
	return 0
}

type JobRunningInfo struct {
	JobID                string          `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	State                JobRunningState `protobuf:"varint,2,opt,name=state,proto3,enum=JobRunningState" json:"state,omitempty"`
	ErrorMsg             string          `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	LastRunningTime      int64           `protobuf:"varint,4,opt,name=lastRunningTime,proto3" json:"lastRunningTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JobRunningInfo) Reset()         { *m = JobRunningInfo{} }
func (m *JobRunningInfo) String() string { return proto.CompactTextString(m) }
func (*JobRunningInfo) ProtoMessage()    {}
func (*JobRunningInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *JobRunningInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRunningInfo.Unmarshal(m, b)
}
func (m *JobRunningInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRunningInfo.Marshal(b, m, deterministic)
}
func (m *JobRunningInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRunningInfo.Merge(m, src)
}
func (m *JobRunningInfo) XXX_Size() int {
	return xxx_messageInfo_JobRunningInfo.Size(m)
}
func (m *JobRunningInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRunningInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JobRunningInfo proto.InternalMessageInfo

func (m *JobRunningInfo) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *JobRunningInfo) GetState() JobRunningState {
	if m != nil {
		return m.State
	}
	return JobRunningState_OK
}

func (m *JobRunningInfo) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *JobRunningInfo) GetLastRunningTime() int64 {
	if m != nil {
		return m.LastRunningTime
	}
	return 0
}

type HeartBeatResponse struct {
	ServerId             string   `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ConfigVersion        int64    `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ServerTime           int32    `protobuf:"varint,3,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatResponse) Reset()         { *m = HeartBeatResponse{} }
func (m *HeartBeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResponse) ProtoMessage()    {}
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *HeartBeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResponse.Unmarshal(m, b)
}
func (m *HeartBeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartBeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResponse.Merge(m, src)
}
func (m *HeartBeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResponse.Size(m)
}
func (m *HeartBeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResponse proto.InternalMessageInfo

func (m *HeartBeatResponse) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *HeartBeatResponse) GetConfigVersion() int64 {
	if m != nil {
		return m.ConfigVersion
	}
	return 0
}

func (m *HeartBeatResponse) GetServerTime() int32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type RegisterRequest struct {
	AgentID              string                       `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	HostName             string                       `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	HostUUID             string                       `protobuf:"bytes,3,opt,name=hostUUID,proto3" json:"hostUUID,omitempty"`
	Os                   string                       `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Platform             string                       `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformFamily       string                       `protobuf:"bytes,6,opt,name=platformFamily,proto3" json:"platformFamily,omitempty"`
	PlatformVersion      string                       `protobuf:"bytes,7,opt,name=platformVersion,proto3" json:"platformVersion,omitempty"`
	KernelVersion        string                       `protobuf:"bytes,8,opt,name=kernelVersion,proto3" json:"kernelVersion,omitempty"`
	VirtualizationSystem string                       `protobuf:"bytes,9,opt,name=virtualizationSystem,proto3" json:"virtualizationSystem,omitempty"`
	VirtualizationRole   string                       `protobuf:"bytes,10,opt,name=virtualizationRole,proto3" json:"virtualizationRole,omitempty"`
	Interfaces           []*RegisterRequest_Interface `protobuf:"bytes,11,rep,name=Interfaces,proto3" json:"Interfaces,omitempty"`
	AgentVersion         string                       `protobuf:"bytes,12,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *RegisterRequest) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *RegisterRequest) GetHostUUID() string {
	if m != nil {
		return m.HostUUID
	}
	return ""
}

func (m *RegisterRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *RegisterRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *RegisterRequest) GetPlatformFamily() string {
	if m != nil {
		return m.PlatformFamily
	}
	return ""
}

func (m *RegisterRequest) GetPlatformVersion() string {
	if m != nil {
		return m.PlatformVersion
	}
	return ""
}

func (m *RegisterRequest) GetKernelVersion() string {
	if m != nil {
		return m.KernelVersion
	}
	return ""
}

func (m *RegisterRequest) GetVirtualizationSystem() string {
	if m != nil {
		return m.VirtualizationSystem
	}
	return ""
}

func (m *RegisterRequest) GetVirtualizationRole() string {
	if m != nil {
		return m.VirtualizationRole
	}
	return ""
}

func (m *RegisterRequest) GetInterfaces() []*RegisterRequest_Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *RegisterRequest) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

type RegisterRequest_Interface struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HardwareAddr         string   `protobuf:"bytes,2,opt,name=hardwareAddr,proto3" json:"hardwareAddr,omitempty"`
	IpAddrs              []string `protobuf:"bytes,3,rep,name=ipAddrs,proto3" json:"ipAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest_Interface) Reset()         { *m = RegisterRequest_Interface{} }
func (m *RegisterRequest_Interface) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest_Interface) ProtoMessage()    {}
func (*RegisterRequest_Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5, 0}
}

func (m *RegisterRequest_Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest_Interface.Unmarshal(m, b)
}
func (m *RegisterRequest_Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest_Interface.Marshal(b, m, deterministic)
}
func (m *RegisterRequest_Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest_Interface.Merge(m, src)
}
func (m *RegisterRequest_Interface) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest_Interface.Size(m)
}
func (m *RegisterRequest_Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest_Interface proto.InternalMessageInfo

func (m *RegisterRequest_Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest_Interface) GetHardwareAddr() string {
	if m != nil {
		return m.HardwareAddr
	}
	return ""
}

func (m *RegisterRequest_Interface) GetIpAddrs() []string {
	if m != nil {
		return m.IpAddrs
	}
	return nil
}

type RegisterResponse struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConfigVersion        int64    `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *RegisterResponse) GetConfigVersion() int64 {
	if m != nil {
		return m.ConfigVersion
	}
	return 0
}

type Job struct {
	JobID                string    `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	RunnerType           JobRunner `protobuf:"varint,2,opt,name=runnerType,proto3,enum=JobRunner" json:"runnerType,omitempty"`
	RunnerModule         string    `protobuf:"bytes,3,opt,name=runnerModule,proto3" json:"runnerModule,omitempty"`
	ModuleVersion        string    `protobuf:"bytes,4,opt,name=moduleVersion,proto3" json:"moduleVersion,omitempty"`
	Interval             int32     `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Config               string    `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	CreateTime           int32     `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int32     `protobuf:"varint,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *Job) GetRunnerType() JobRunner {
	if m != nil {
		return m.RunnerType
	}
	return JobRunner_Telegraf
}

func (m *Job) GetRunnerModule() string {
	if m != nil {
		return m.RunnerModule
	}
	return ""
}

func (m *Job) GetModuleVersion() string {
	if m != nil {
		return m.ModuleVersion
	}
	return ""
}

func (m *Job) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Job) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *Job) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Job) GetUpdateTime() int32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type GetJobsRequest struct {
	AgentID              string   `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsRequest) Reset()         { *m = GetJobsRequest{} }
func (m *GetJobsRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobsRequest) ProtoMessage()    {}
func (*GetJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *GetJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsRequest.Unmarshal(m, b)
}
func (m *GetJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsRequest.Marshal(b, m, deterministic)
}
func (m *GetJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsRequest.Merge(m, src)
}
func (m *GetJobsRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobsRequest.Size(m)
}
func (m *GetJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsRequest proto.InternalMessageInfo

func (m *GetJobsRequest) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

type GetJobsResponse struct {
	ConfigVersion        int64    `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Jobs                 []*Job   `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsResponse) Reset()         { *m = GetJobsResponse{} }
func (m *GetJobsResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobsResponse) ProtoMessage()    {}
func (*GetJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *GetJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsResponse.Unmarshal(m, b)
}
func (m *GetJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsResponse.Marshal(b, m, deterministic)
}
func (m *GetJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsResponse.Merge(m, src)
}
func (m *GetJobsResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobsResponse.Size(m)
}
func (m *GetJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsResponse proto.InternalMessageInfo

func (m *GetJobsResponse) GetConfigVersion() int64 {
	if m != nil {
		return m.ConfigVersion
	}
	return 0
}

func (m *GetJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type AddJobRequest struct {
	AgentID              string    `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	RunnerType           JobRunner `protobuf:"varint,2,opt,name=runnerType,proto3,enum=JobRunner" json:"runnerType,omitempty"`
	RunnerModule         string    `protobuf:"bytes,3,opt,name=runnerModule,proto3" json:"runnerModule,omitempty"`
	ModuleVersion        string    `protobuf:"bytes,4,opt,name=moduleVersion,proto3" json:"moduleVersion,omitempty"`
	Interval             int32     `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Config               string    `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddJobRequest) Reset()         { *m = AddJobRequest{} }
func (m *AddJobRequest) String() string { return proto.CompactTextString(m) }
func (*AddJobRequest) ProtoMessage()    {}
func (*AddJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *AddJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddJobRequest.Unmarshal(m, b)
}
func (m *AddJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddJobRequest.Marshal(b, m, deterministic)
}
func (m *AddJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddJobRequest.Merge(m, src)
}
func (m *AddJobRequest) XXX_Size() int {
	return xxx_messageInfo_AddJobRequest.Size(m)
}
func (m *AddJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddJobRequest proto.InternalMessageInfo

func (m *AddJobRequest) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *AddJobRequest) GetRunnerType() JobRunner {
	if m != nil {
		return m.RunnerType
	}
	return JobRunner_Telegraf
}

func (m *AddJobRequest) GetRunnerModule() string {
	if m != nil {
		return m.RunnerModule
	}
	return ""
}

func (m *AddJobRequest) GetModuleVersion() string {
	if m != nil {
		return m.ModuleVersion
	}
	return ""
}

func (m *AddJobRequest) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *AddJobRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type AddJobResponse struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddJobResponse) Reset()         { *m = AddJobResponse{} }
func (m *AddJobResponse) String() string { return proto.CompactTextString(m) }
func (*AddJobResponse) ProtoMessage()    {}
func (*AddJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *AddJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddJobResponse.Unmarshal(m, b)
}
func (m *AddJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddJobResponse.Marshal(b, m, deterministic)
}
func (m *AddJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddJobResponse.Merge(m, src)
}
func (m *AddJobResponse) XXX_Size() int {
	return xxx_messageInfo_AddJobResponse.Size(m)
}
func (m *AddJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddJobResponse proto.InternalMessageInfo

func (m *AddJobResponse) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type DelJobRequest struct {
	AgentID              string   `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	JobID                string   `protobuf:"bytes,2,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelJobRequest) Reset()         { *m = DelJobRequest{} }
func (m *DelJobRequest) String() string { return proto.CompactTextString(m) }
func (*DelJobRequest) ProtoMessage()    {}
func (*DelJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *DelJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelJobRequest.Unmarshal(m, b)
}
func (m *DelJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelJobRequest.Marshal(b, m, deterministic)
}
func (m *DelJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelJobRequest.Merge(m, src)
}
func (m *DelJobRequest) XXX_Size() int {
	return xxx_messageInfo_DelJobRequest.Size(m)
}
func (m *DelJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelJobRequest proto.InternalMessageInfo

func (m *DelJobRequest) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *DelJobRequest) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type DelJobResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelJobResponse) Reset()         { *m = DelJobResponse{} }
func (m *DelJobResponse) String() string { return proto.CompactTextString(m) }
func (*DelJobResponse) ProtoMessage()    {}
func (*DelJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *DelJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelJobResponse.Unmarshal(m, b)
}
func (m *DelJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelJobResponse.Marshal(b, m, deterministic)
}
func (m *DelJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelJobResponse.Merge(m, src)
}
func (m *DelJobResponse) XXX_Size() int {
	return xxx_messageInfo_DelJobResponse.Size(m)
}
func (m *DelJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelJobResponse proto.InternalMessageInfo

func (m *DelJobResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type Foo struct {
	Bar                  int32                `protobuf:"varint,1,opt,name=bar,proto3" json:"bar,omitempty"`
	Baz                  *wrappers.Int32Value `protobuf:"bytes,2,opt,name=baz,proto3" json:"baz,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetBar() int32 {
	if m != nil {
		return m.Bar
	}
	return 0
}

func (m *Foo) GetBaz() *wrappers.Int32Value {
	if m != nil {
		return m.Baz
	}
	return nil
}

func init() {
	proto.RegisterEnum("JobRunningState", JobRunningState_name, JobRunningState_value)
	proto.RegisterEnum("JobRunner", JobRunner_name, JobRunner_value)
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterType((*FileChunk)(nil), "FileChunk")
	proto.RegisterType((*HeartBeatRequest)(nil), "HeartBeatRequest")
	proto.RegisterType((*JobRunningInfo)(nil), "JobRunningInfo")
	proto.RegisterType((*HeartBeatResponse)(nil), "HeartBeatResponse")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterRequest_Interface)(nil), "RegisterRequest.Interface")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*GetJobsRequest)(nil), "GetJobsRequest")
	proto.RegisterType((*GetJobsResponse)(nil), "GetJobsResponse")
	proto.RegisterType((*AddJobRequest)(nil), "AddJobRequest")
	proto.RegisterType((*AddJobResponse)(nil), "AddJobResponse")
	proto.RegisterType((*DelJobRequest)(nil), "DelJobRequest")
	proto.RegisterType((*DelJobResponse)(nil), "DelJobResponse")
	proto.RegisterType((*Foo)(nil), "Foo")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 969 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x5f, 0x6f, 0xdb, 0x36,
	0x10, 0xaf, 0xff, 0x5b, 0x97, 0x58, 0x56, 0x88, 0x62, 0xd0, 0x54, 0xa0, 0x0b, 0xd4, 0x2e, 0x48,
	0x8d, 0x4d, 0xd9, 0xdc, 0xb7, 0xbd, 0x6c, 0xdd, 0xbc, 0xac, 0xce, 0xd0, 0x0d, 0x50, 0xd3, 0xbe,
	0x0d, 0x01, 0x1d, 0x9d, 0x65, 0xb5, 0xb2, 0xe8, 0x92, 0x74, 0x82, 0xe4, 0x7d, 0xdf, 0x60, 0x2f,
	0xfb, 0x0a, 0xfb, 0x3a, 0xfb, 0x42, 0x03, 0x49, 0x51, 0xb1, 0x9c, 0x0c, 0xe9, 0x6b, 0x9f, 0xcc,
	0xfb, 0xdd, 0x89, 0xe4, 0xdd, 0xef, 0x77, 0x47, 0xc3, 0x60, 0x89, 0x42, 0xd0, 0x14, 0xa3, 0x15,
	0x67, 0x92, 0x05, 0x8f, 0x53, 0xc6, 0xd2, 0x1c, 0x8f, 0xb4, 0x35, 0x5b, 0xcf, 0x8f, 0x2e, 0x39,
	0x5d, 0xad, 0x90, 0x0b, 0xe3, 0x0f, 0x7f, 0x80, 0xf6, 0x71, 0x96, 0x23, 0x79, 0x04, 0xce, 0x3c,
	0xcb, 0xf1, 0xac, 0xa0, 0x4b, 0xf4, 0x1b, 0xfb, 0x8d, 0x43, 0x27, 0xee, 0x2b, 0xe0, 0x37, 0xba,
	0xd4, 0x4e, 0xb1, 0xa0, 0xdf, 0x9e, 0x2d, 0xa8, 0x58, 0xf8, 0x4d, 0xe3, 0x54, 0xc0, 0x4b, 0x2a,
	0x16, 0xe1, 0x17, 0xe0, 0xa8, 0x1d, 0x7e, 0x5a, 0xac, 0x8b, 0xf7, 0x84, 0x40, 0x3b, 0xa1, 0x92,
	0xea, 0x1d, 0x76, 0x63, 0xbd, 0x0e, 0x3f, 0x80, 0xf7, 0x12, 0x29, 0x97, 0x3f, 0x22, 0x95, 0x31,
	0x7e, 0x58, 0xa3, 0x90, 0xc4, 0x87, 0x1e, 0x4d, 0xb1, 0x90, 0xd3, 0x49, 0x79, 0x98, 0x35, 0xc9,
	0x13, 0x68, 0xbf, 0x63, 0x33, 0xe1, 0x37, 0xf7, 0x5b, 0x87, 0x3b, 0xe3, 0x61, 0x74, 0xc2, 0x66,
	0xf1, 0xba, 0x28, 0xb2, 0x22, 0x9d, 0x16, 0x73, 0x16, 0x6b, 0x27, 0x79, 0x0c, 0x70, 0x9e, 0x67,
	0x58, 0xc8, 0xd3, 0x6c, 0x89, 0x7e, 0x6b, 0xbf, 0x71, 0xd8, 0x8a, 0x37, 0x90, 0xf0, 0xaf, 0x06,
	0xb8, 0xf5, 0x0f, 0xc9, 0x43, 0xe8, 0xbc, 0x63, 0xb3, 0xea, 0x3c, 0x63, 0x90, 0x03, 0xe8, 0x08,
	0x49, 0x25, 0xea, 0xac, 0xdc, 0xb1, 0xb7, 0x71, 0xdc, 0x6b, 0x85, 0xc7, 0xc6, 0x4d, 0x02, 0xe8,
	0x23, 0xe7, 0x8c, 0xbf, 0x12, 0xa9, 0x3e, 0xce, 0x89, 0x2b, 0x9b, 0x1c, 0xc2, 0x30, 0xa7, 0x42,
	0x96, 0x9f, 0xe9, 0x1b, 0xb5, 0xf5, 0x8d, 0xb6, 0xe1, 0xf0, 0x12, 0xf6, 0x36, 0x2a, 0x21, 0x56,
	0xac, 0x10, 0xa6, 0xb8, 0xc8, 0x2f, 0x90, 0x9f, 0x65, 0x89, 0xad, 0xbc, 0x01, 0xa6, 0x09, 0xf9,
	0x12, 0xdc, 0x73, 0x56, 0xcc, 0xb3, 0xf4, 0xec, 0x02, 0xb9, 0xc8, 0x58, 0xa1, 0x2f, 0xda, 0x8a,
	0x07, 0x06, 0x7d, 0x6b, 0x40, 0x55, 0x0f, 0xf3, 0x49, 0x55, 0x8f, 0x4e, 0xbc, 0x81, 0x84, 0xff,
	0xb4, 0x61, 0x18, 0x63, 0x9a, 0x09, 0x89, 0xfc, 0x7e, 0x0a, 0x02, 0xe8, 0x2f, 0x98, 0x90, 0x8a,
	0x7a, 0xcb, 0xb6, 0xb5, 0xad, 0xef, 0xcd, 0x9b, 0xe9, 0xc4, 0x16, 0xc2, 0xda, 0xc4, 0x85, 0x26,
	0x13, 0x3a, 0x77, 0x27, 0x6e, 0x32, 0xa1, 0x62, 0x57, 0x39, 0x95, 0x73, 0xc6, 0x97, 0x7e, 0xc7,
	0xc4, 0x5a, 0x9b, 0x1c, 0x80, 0x6b, 0xd7, 0xc7, 0x74, 0x99, 0xe5, 0x57, 0x7e, 0x57, 0x47, 0x6c,
	0xa1, 0xaa, 0xb8, 0x16, 0x29, 0x93, 0xf5, 0x7b, 0x3a, 0x70, 0x1b, 0x26, 0x4f, 0x61, 0xf0, 0x1e,
	0x79, 0x81, 0xb9, 0x8d, 0xeb, 0xeb, 0xb8, 0x3a, 0x48, 0xc6, 0xf0, 0xf0, 0x22, 0xe3, 0x72, 0x4d,
	0xf3, 0xec, 0x9a, 0xca, 0x8c, 0x15, 0xaf, 0xaf, 0x84, 0xc4, 0xa5, 0xef, 0xe8, 0xe0, 0x3b, 0x7d,
	0x24, 0x02, 0x52, 0xc7, 0x63, 0x96, 0xa3, 0x0f, 0xfa, 0x8b, 0x3b, 0x3c, 0xe4, 0x3b, 0x80, 0x69,
	0x21, 0x91, 0xcf, 0xe9, 0x39, 0x0a, 0x7f, 0x47, 0x0b, 0x39, 0x88, 0xb6, 0xea, 0x1f, 0x55, 0x21,
	0xf1, 0x46, 0x34, 0x09, 0x61, 0x57, 0xd3, 0x60, 0x93, 0xd8, 0xd5, 0xa7, 0xd4, 0xb0, 0xe0, 0x0f,
	0x70, 0xaa, 0x2f, 0x54, 0xc7, 0x6d, 0xf4, 0xac, 0x5e, 0xab, 0x4d, 0x16, 0x94, 0x27, 0x97, 0x94,
	0xe3, 0x8b, 0x24, 0xe1, 0x25, 0x89, 0x35, 0x4c, 0xd1, 0x9f, 0xad, 0xd4, 0x4a, 0xf8, 0xad, 0xfd,
	0x96, 0xa2, 0xbf, 0x34, 0xc3, 0x53, 0xf0, 0x6e, 0xee, 0x5a, 0x8a, 0xf4, 0x73, 0xe8, 0xeb, 0x2b,
	0xdc, 0x68, 0xb4, 0x54, 0xcb, 0xc7, 0x4a, 0x34, 0xfc, 0xb3, 0x09, 0xad, 0x13, 0x36, 0xfb, 0x9f,
	0x3e, 0x1c, 0x01, 0xf0, 0x75, 0x51, 0x20, 0x3f, 0xbd, 0x5a, 0xd9, 0x66, 0x04, 0xdb, 0x8c, 0xc8,
	0xe3, 0x0d, 0xaf, 0xca, 0xce, 0x58, 0xaf, 0x58, 0xb2, 0xce, 0xb1, 0x94, 0x61, 0x0d, 0x53, 0x62,
	0x58, 0xea, 0x95, 0xad, 0xa3, 0x51, 0x65, 0x1d, 0x54, 0x02, 0xcd, 0x54, 0x21, 0x2f, 0x68, 0xae,
	0x05, 0xda, 0x89, 0x2b, 0x9b, 0x7c, 0x06, 0x5d, 0x93, 0x40, 0x29, 0xcc, 0xd2, 0xd2, 0xa3, 0x87,
	0x23, 0x95, 0xa8, 0x5b, 0xad, 0x67, 0x5a, 0xed, 0x06, 0x51, 0xfe, 0xf5, 0x2a, 0xb1, 0xfe, 0xbe,
	0xf1, 0xdf, 0x20, 0xe1, 0x08, 0xdc, 0x5f, 0x50, 0x9e, 0xb0, 0x99, 0xb8, 0xb7, 0x11, 0xc3, 0x18,
	0x86, 0x55, 0x6c, 0x49, 0xc4, 0xed, 0x6a, 0x37, 0xee, 0x1a, 0x08, 0x7e, 0x6d, 0x8a, 0xb6, 0x75,
	0x25, 0x35, 0x12, 0xfe, 0xdb, 0x80, 0xc1, 0x8b, 0x24, 0x51, 0xc0, 0xbd, 0x83, 0xe0, 0x93, 0x61,
	0x25, 0x3c, 0x00, 0xd7, 0x26, 0x55, 0x16, 0xea, 0x4e, 0x9d, 0x85, 0xdf, 0xc3, 0x60, 0x82, 0xf9,
	0x47, 0x25, 0x5f, 0x6d, 0xd0, 0xdc, 0xdc, 0x60, 0x04, 0xae, 0xdd, 0xa0, 0x3c, 0xc8, 0x87, 0x5e,
	0x82, 0x39, 0x4a, 0x34, 0x9d, 0xd1, 0x8f, 0xad, 0x19, 0x1e, 0x43, 0xeb, 0x98, 0x31, 0xe2, 0x41,
	0x6b, 0x46, 0xb9, 0x76, 0x76, 0x62, 0xb5, 0x24, 0x5f, 0x2b, 0xe4, 0x5a, 0x6f, 0xbc, 0x33, 0x7e,
	0x14, 0x99, 0x27, 0x3a, 0xb2, 0x4f, 0xb4, 0x9a, 0x0c, 0xcf, 0xc7, 0x6f, 0x69, 0xbe, 0x46, 0x15,
	0x7e, 0x3d, 0x7a, 0x0a, 0xc3, 0xad, 0x67, 0x89, 0x74, 0xa1, 0xf9, 0xfb, 0xaf, 0xde, 0x03, 0xe2,
	0x40, 0xe7, 0x67, 0xf5, 0x0e, 0x79, 0x8d, 0xd1, 0x01, 0x38, 0x15, 0x33, 0x64, 0x17, 0xfa, 0xa7,
	0x98, 0x63, 0xca, 0xe9, 0xdc, 0x7b, 0x40, 0x76, 0xa0, 0x37, 0xa1, 0x92, 0x26, 0x2c, 0xf5, 0x1a,
	0xe3, 0xbf, 0x9b, 0xe0, 0xa4, 0x3c, 0x2b, 0x52, 0x26, 0xa5, 0x20, 0x63, 0x70, 0xaa, 0x27, 0x89,
	0xec, 0x45, 0xdb, 0x0f, 0x75, 0x40, 0xa2, 0xdb, 0x2f, 0xd6, 0x13, 0xd8, 0x9d, 0xb0, 0xcb, 0x22,
	0x67, 0x34, 0xd1, 0xff, 0x1d, 0x3a, 0x91, 0xfa, 0x09, 0x20, 0xaa, 0xfe, 0x07, 0x7c, 0xd3, 0x20,
	0x47, 0xd0, 0xb7, 0x53, 0x84, 0x78, 0xdb, 0xc3, 0x2f, 0xd8, 0x8b, 0x6e, 0x8d, 0x98, 0xaf, 0xa0,
	0x57, 0x8a, 0x9d, 0x0c, 0xa3, 0x7a, 0x8b, 0x04, 0x5e, 0xb4, 0xdd, 0x07, 0xcf, 0xa0, 0x6b, 0x08,
	0x27, 0x6e, 0x54, 0x93, 0x73, 0x30, 0x8c, 0xb6, 0x94, 0xf0, 0x0c, 0xba, 0x86, 0x32, 0xe2, 0x46,
	0x35, 0xf2, 0x83, 0x61, 0x54, 0xe7, 0x72, 0xd6, 0xd5, 0x1c, 0x3c, 0xff, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x1c, 0x5e, 0xa1, 0x61, 0x45, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GringottsClient is the client API for Gringotts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GringottsClient interface {
	HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error)
	DownloadFile(ctx context.Context, in *File, opts ...grpc.CallOption) (Gringotts_DownloadFileClient, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsResponse, error)
	AddJob(ctx context.Context, in *AddJobRequest, opts ...grpc.CallOption) (*AddJobResponse, error)
	DelJob(ctx context.Context, in *DelJobRequest, opts ...grpc.CallOption) (*DelJobResponse, error)
}

type gringottsClient struct {
	cc *grpc.ClientConn
}

func NewGringottsClient(cc *grpc.ClientConn) GringottsClient {
	return &gringottsClient{cc}
}

func (c *gringottsClient) HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error) {
	out := new(HeartBeatResponse)
	err := c.cc.Invoke(ctx, "/gringotts/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gringottsClient) DownloadFile(ctx context.Context, in *File, opts ...grpc.CallOption) (Gringotts_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gringotts_serviceDesc.Streams[0], "/gringotts/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &gringottsDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gringotts_DownloadFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type gringottsDownloadFileClient struct {
	grpc.ClientStream
}

func (x *gringottsDownloadFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gringottsClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/gringotts/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gringottsClient) GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsResponse, error) {
	out := new(GetJobsResponse)
	err := c.cc.Invoke(ctx, "/gringotts/GetJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gringottsClient) AddJob(ctx context.Context, in *AddJobRequest, opts ...grpc.CallOption) (*AddJobResponse, error) {
	out := new(AddJobResponse)
	err := c.cc.Invoke(ctx, "/gringotts/AddJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gringottsClient) DelJob(ctx context.Context, in *DelJobRequest, opts ...grpc.CallOption) (*DelJobResponse, error) {
	out := new(DelJobResponse)
	err := c.cc.Invoke(ctx, "/gringotts/DelJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GringottsServer is the server API for Gringotts service.
type GringottsServer interface {
	HeartBeat(context.Context, *HeartBeatRequest) (*HeartBeatResponse, error)
	DownloadFile(*File, Gringotts_DownloadFileServer) error
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetJobs(context.Context, *GetJobsRequest) (*GetJobsResponse, error)
	AddJob(context.Context, *AddJobRequest) (*AddJobResponse, error)
	DelJob(context.Context, *DelJobRequest) (*DelJobResponse, error)
}

// UnimplementedGringottsServer can be embedded to have forward compatible implementations.
type UnimplementedGringottsServer struct {
}

func (*UnimplementedGringottsServer) HeartBeat(ctx context.Context, req *HeartBeatRequest) (*HeartBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (*UnimplementedGringottsServer) DownloadFile(req *File, srv Gringotts_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (*UnimplementedGringottsServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedGringottsServer) GetJobs(ctx context.Context, req *GetJobsRequest) (*GetJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (*UnimplementedGringottsServer) AddJob(ctx context.Context, req *AddJobRequest) (*AddJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddJob not implemented")
}
func (*UnimplementedGringottsServer) DelJob(ctx context.Context, req *DelJobRequest) (*DelJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelJob not implemented")
}

func RegisterGringottsServer(s *grpc.Server, srv GringottsServer) {
	s.RegisterService(&_Gringotts_serviceDesc, srv)
}

func _Gringotts_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GringottsServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gringotts/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GringottsServer).HeartBeat(ctx, req.(*HeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gringotts_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(File)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GringottsServer).DownloadFile(m, &gringottsDownloadFileServer{stream})
}

type Gringotts_DownloadFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type gringottsDownloadFileServer struct {
	grpc.ServerStream
}

func (x *gringottsDownloadFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _Gringotts_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GringottsServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gringotts/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GringottsServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gringotts_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GringottsServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gringotts/GetJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GringottsServer).GetJobs(ctx, req.(*GetJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gringotts_AddJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GringottsServer).AddJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gringotts/AddJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GringottsServer).AddJob(ctx, req.(*AddJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gringotts_DelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GringottsServer).DelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gringotts/DelJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GringottsServer).DelJob(ctx, req.(*DelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gringotts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gringotts",
	HandlerType: (*GringottsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartBeat",
			Handler:    _Gringotts_HeartBeat_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Gringotts_Register_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _Gringotts_GetJobs_Handler,
		},
		{
			MethodName: "AddJob",
			Handler:    _Gringotts_AddJob_Handler,
		},
		{
			MethodName: "DelJob",
			Handler:    _Gringotts_DelJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _Gringotts_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}
